project:
  type: website
  output-dir: docs
  preview:
    port: 5896
    browser: true
  render:
    - "*.qmd"
  resources:
    - "showcase/"

website:
  title: Exploratory Data Analysis
  site-url: https://eda.seas.gwu.edu/
  favicon: images/favicon.ico
  repo-url: https://github.com/emse-eda-gwu/
  description: 'Course website for the EMSE course "Exploratory Data Analysis" at GWU'
  search: true
  open-graph:
    locale: es_ES
    site-name: https://eda.seas.gwu.edu/
  twitter-card:
    creator: "@johnhelveston"
    site: "@johnhelveston"
    image: "images/eda_hex_sticker_square.png"
    card-style: summary
  navbar:
    title: ""
    left:
      - text: ""
        icon: fas fa-home
        href: index.html
      - text: "Select Section"
        menu:
          - text: "Spring 2020"
            href: http://eda.seas.gwu.edu/2020-Spring/
          - text: "Spring 2021"
            href: http://eda.seas.gwu.edu/2021-Spring/
          - text: "Fall 2022"
            href: http://eda.seas.gwu.edu/2022-Fall/
      - text: "Project Showcase"
        menu:
          - text: "Spring 2020"
            href: showcase/2020-spring.qmd
          - text: "Spring 2021"
            href: showcase/2021-spring.qmd
          - text: "Fall 2022"
            href: showcase/2022-fall.qmd
    right:
    - icon: fas fa-bars
      menu:
      - text: About
        icon: fas fa-info-circle
        href: about.qmd
      - text: License
        icon: fas fa-gavel
        href: LICENSE.qmd
      - text: Contact
        icon: fas fa-envelope
        href: mailto:jph@gwu.edu
      - text: Source files
        icon: fab fa-github
        href: https://github.com/emse-eda-gwu/
  page-footer:
    center:
      - text: '<a href="LICENSE.html">LICENSE: CC-BY-SA <i class="fab fa-creative-commons"></i><i class="fab fa-creative-commons-by"></i><i class="fab fa-creative-commons-sa"></i></a>'

format:
  html:
    theme: darkly
    css: styles.css
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: false
    include-in-header: "_includes/header.html"
